# Base configs
baseurl: "https://photography.karlemstrand-test.cf"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-159402018-1"

# UI configs
title: "Photography by Roderick karlemstrand"
subtitle: "See the world through my eyes!"
author: "2020 Roderick Karlemstrand All Rights Reserved."
header:
 title: "Karlemstrand Photography"
 subtitle: "Just another photo enthusiast's expensive hobby"
footer:
 name: "Roderick Karlemstrand"
 bio: "I work full-time as an IT Consultant at a state owned financial company but can easily transform to a photo enthusiast after work."

social_urls:
  facebook: "https://www.facebook.com/Roderick.Lindsberg.Karlemstrand"
  linkedin: "http://linkedin.com/in/roderick-karlemstrand/"
  github: "https://www.github.com/rlindsberg"

plugins:
  - jekyll-gzip
